
language: python

os: 
    - osx
    - linux

python:
    - "2.7"

virtualenv:
    system_site_packages: true

before_install:
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy scipy matplotlib pip nose vtk
    - conda install --yes -c https://conda.anaconda.org/dlr-sc pythonocc-core
    - pip install setuptools
    - pip install enum34
    - pip install numpy-stl
    - pip install coveralls
    - pip install coverage
    - python setup.py install

script: coverage run test.py

after_success:
    - coveralls

branches:
    only:
        - master
